### PR TITLE
Support custom message

### PR DESCRIPTION
**Pull request by spesnova**
## What does this PR do?

- Refactor `run.rb`
- **Change default message and icon** (see example in [`README`](https://github.com/spesnova/step-pretty-slack-notify/blob/support-custom-message/README.md))
- Support to define additional message on `passed` or `failed`
- Update `slack-notifier` to `1.5.1`
- Bump up the version to `0.3.0`

This PR closes https://github.com/wantedly/step-pretty-slack-notify/issues/27

## Motivation
To allow users to define additional message like this:

slack

## References

- [Predefined After Step Variables](http://devcenter.wercker.com/docs/environment-variables/after-step-variables)
- [Available Environment Variables](http://devcenter.wercker.com/docs/environment-variables/available-env-vars)
- [Basic message formatting | Slack](https://api.slack.com/docs/message-formatting)
- [stevenosloan/slack-notifier: A simple wrapper for posting to slack channels](https://github.com/stevenosloan/slack-notifier)

### CODE REVIEW

**Comment by spesnova** [comment]
@dtan4 @koudaiii @awakia :octocat:

**Comment by dtan4** [comment]
LGTM 👍 Thanks ❗️

**Comment by spesnova** [comment]
@dtan4 Please don't forget to deployed to wercker-directory and check it the step works correctly 🙏

**Comment by dtan4** [comment]
Thank you! 0.3.0 was just released :shipit: 

image

**Comment by koudaiii** [comment]
🎉 🎉 🎉

**Comment by spesnova** [comment]
> Thank you! 0.3.0 was just released

Thanks guys 👍 
@dtan4 @koudaiii Can you find it works correctly on your slack?

**Comment by dtan4** [comment]
Unfortunally, it does NOT work correctly because of difference of installed gem version...

This will be fixed at #37, please wait for a moment 👷

**Comment by dtan4** [comment]
OK, it works fine with 0.3.1 

image

**Pull request merged**
